function storageWeightText(value){const n=Number(value||0);return `${n.toFixed(n<10?2:1)}kg`;}
async function upsertStorage(playerId,itemId,quantity){const {data:row,error}=await supabaseClient.from('player_storage').select('id,quantity').eq('player_id',playerId).eq('item_id',itemId).maybeSingle();if(error)throw error;const result=row?await supabaseClient.from('player_storage').update({quantity:Number(row.quantity)+Number(quantity)}).eq('id',row.id):await supabaseClient.from('player_storage').insert({player_id:playerId,item_id:itemId,quantity});if(result.error)throw result.error;}
async function loadStorage(){
 const {data:{user}}=await supabaseClient.auth.getUser();if(!user)return;
 const {data:rows}=await supabaseClient.from('player_storage').select('item_id,quantity,items(name,type,weight_kg)').eq('player_id',user.id).gt('quantity',0);
 const groups={Wood:[],Ore:[],Metal:[],Food:[],Barrels:[],Other:[]};
 for(const r of rows||[]){const n=r.items?.name||'Unknown',type=(r.items?.type||'').toLowerCase();const g=n.includes('Log')||n.includes('Plank')||n.includes('Beam')||n.includes('Stick')?'Wood':n.includes('Ore')||n.includes('Bog')||n.includes('Rock')?'Ore':n.includes('Iron')||n.includes('Hoop')||n.includes('Nail')?'Metal':n.includes('Mead')||n.includes('Barrel')?'Barrels':type.includes('food')?'Food':'Other';groups[g].push(r);}
 document.getElementById('storage-cards').innerHTML=Object.entries(groups).map(([g,v])=>`<div class="card"><h3>${g}</h3>${v.map(x=>`<div class="transport-item-row"><span>${x.items?.name}: ${x.quantity}<small> · ${storageWeightText(Number(x.quantity)*Number(x.items?.weight_kg||0))}</small></span><button onclick="loadFromStorage(${x.item_id},1,'backpack')">Load 1 to Backpack</button><button onclick="loadFromStorage(${x.item_id},1,'cart')">Load 1 to Transport</button></div>`).join('')||'<p>Empty</p>'}</div>`).join('');
 const [{data:cart},{data:backpack}]=await Promise.all([supabaseClient.from('player_carts').select('*').eq('player_id',user.id).eq('is_active',true).maybeSingle(),supabaseClient.from('inventory').select('quantity,items(name,weight_kg)').eq('player_id',user.id).gt('quantity',0)]);
 let html='<h4>Backpack</h4>'+((backpack||[]).map(x=>`<p>${x.items?.name}: ${x.quantity} (${storageWeightText(Number(x.quantity)*Number(x.items?.weight_kg||0))})</p>`).join('')||'<p>Empty</p>');
 if(cart){const {data:items}=await supabaseClient.from('cart_items').select('quantity,items(name,weight_kg)').eq('cart_id',cart.id);html+=`<h4>${cart.name}</h4>`+((items||[]).map(x=>`<p>${x.items?.name}: ${x.quantity} (${storageWeightText(Number(x.quantity)*Number(x.items?.weight_kg||0))})</p>`).join('')||'<p>Empty</p>');}else html+='<h4>Transport</h4><p>No active transport. Repair the handcart in your Wagon Shed.</p>';
 document.getElementById('storage-cart').innerHTML=html;
}
async function loadFromStorage(itemId,amount,destination){const {data:{user}}=await supabaseClient.auth.getUser();try{const {data,error}=await supabaseClient.rpc('load_storage_item',{p_item_id:itemId,p_quantity:amount,p_destination:destination});if(error)throw error;document.getElementById('storage-message').innerText=`✅ Loaded ${data.quantity} item into ${destination}.`;await loadStorage();}catch(e){document.getElementById('storage-message').innerText='❌ '+e.message;}}
async function unloadCart(){const {data:{user}}=await supabaseClient.auth.getUser();const {data:cart}=await supabaseClient.from('player_carts').select('id').eq('player_id',user.id).eq('is_active',true).maybeSingle();if(!cart){document.getElementById('storage-message').innerText='No active transport.';return;}const {data:items}=await supabaseClient.from('cart_items').select('*').eq('cart_id',cart.id);for(const item of items||[])await upsertStorage(user.id,item.item_id,item.quantity);await supabaseClient.from('cart_items').delete().eq('cart_id',cart.id);document.getElementById('storage-message').innerText='✅ Transport unloaded into storage.';loadStorage();}
async function unloadBackpack(){const {data:{user}}=await supabaseClient.auth.getUser();const {data:items}=await supabaseClient.from('inventory').select('*').eq('player_id',user.id).gt('quantity',0);for(const item of items||[])await upsertStorage(user.id,item.item_id,item.quantity);await supabaseClient.from('inventory').delete().eq('player_id',user.id);document.getElementById('storage-message').innerText='✅ Backpack unloaded into storage.';loadStorage();}
document.getElementById('unload-cart-button')?.addEventListener('click',unloadCart);document.getElementById('unload-backpack-button')?.addEventListener('click',unloadBackpack);loadStorage();
