"use strict";
let tradeItems=[];
function barterMessage(text,type="info"){const el=document.getElementById("barter-message");if(!el)return;el.className=`barter-message ${type}`;el.textContent=text;}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");}
function groupedOptions(items){const groups={};for(const item of items){const key=String(item.category||"Other").replaceAll("_"," ");(groups[key]??=[]).push(item);}return Object.entries(groups).map(([group,rows])=>`<optgroup label="${esc(group.replace(/\b\w/g,c=>c.toUpperCase()))}">${rows.map(item=>`<option value="${item.id}">${esc(item.name)} — ${Number(item.value).toLocaleString("en-GB")} value (${Number(item.owned||0).toLocaleString()} owned)</option>`).join("")}</optgroup>`).join("");}
function selected(id){return tradeItems.find(item=>String(item.id)===String(document.getElementById(id)?.value));}
function updateTradePreview(){const sell=selected("trade-sell-item"),buy=selected("trade-buy-item"),qty=Math.max(1,Math.floor(Number(document.getElementById("trade-sell-quantity")?.value||1)));const preview=document.getElementById("trade-preview"),button=document.getElementById("complete-trade-button");if(!preview||!sell||!buy)return;const sellValue=Math.max(0,Number(sell.value||0)),buyValue=Math.max(1,Number(buy.value||0)),value=qty*sellValue,receive=Math.floor(value/buyValue),needed=Math.ceil(buyValue/Math.max(1,sellValue));const enoughOwned=qty<=Number(sell.owned||0);if(receive<1){preview.innerHTML=`<strong>Offer value: ${value.toLocaleString("en-GB")}</strong><span>You receive 0 ${esc(buy.name)}. You need at least ${needed.toLocaleString("en-GB")} ${esc(sell.name)} for 1 ${esc(buy.name)}.</span>`;}else{preview.innerHTML=`<strong>Offer value: ${value.toLocaleString("en-GB")}</strong><span>You receive ${receive.toLocaleString("en-GB")} ${esc(buy.name)}. Any leftover value is not converted into half items.</span>`;}if(button){button.disabled=receive<1||!enoughOwned||sell.id===buy.id;button.textContent=!enoughOwned?"Not Enough Items":receive<1?"Offer Too Small":"Complete Barter";}}
async function loadBarter(){try{const{data:{user}}=await supabaseClient.auth.getUser();if(!user){location.href="login.html";return;}const{data,error}=await supabaseClient.rpc("get_trade_catalog");if(error)throw error;tradeItems=Array.isArray(data)?data:[];const options=groupedOptions(tradeItems);document.getElementById("trade-sell-item").innerHTML=options;document.getElementById("trade-buy-item").innerHTML=options;const firstOwned=tradeItems.find(x=>Number(x.owned)>0);if(firstOwned)document.getElementById("trade-sell-item").value=firstOwned.id;const firstDifferent=tradeItems.find(x=>!firstOwned||x.id!==firstOwned.id);if(firstDifferent)document.getElementById("trade-buy-item").value=firstDifferent.id;updateTradePreview();}catch(error){console.error(error);barterMessage(`❌ ${error.message}`,"error");}}
async function completeValueTrade(){const sell=selected("trade-sell-item"),buy=selected("trade-buy-item"),quantity=Math.max(1,Math.floor(Number(document.getElementById("trade-sell-quantity")?.value||1)));if(!sell||!buy)return;const receive=Math.floor((quantity*Number(sell.value||0))/Math.max(1,Number(buy.value||0)));if(receive<1){barterMessage(`❌ You need a larger offer to receive at least 1 ${buy.name}.`,"error");return;}try{barterMessage("Completing trade…");const{data,error}=await supabaseClient.rpc("complete_value_trade",{p_sell_item:Number(sell.id),p_sell_quantity:quantity,p_buy_item:Number(buy.id)});if(error)throw error;barterMessage(`✅ Traded ${data.sold_quantity} ${data.sold_name} for ${data.received_quantity} ${data.received_name}.`,"success");await loadBarter();}catch(error){barterMessage(`❌ ${error.message}`,"error");}}
["trade-sell-item","trade-buy-item","trade-sell-quantity"].forEach(id=>document.getElementById(id)?.addEventListener("input",updateTradePreview));document.getElementById("complete-trade-button")?.addEventListener("click",completeValueTrade);loadBarter();
