let trainingBusy = false;
const trainingStats = [
  { key: "strength", icon: "💪", name: "Strength", text: "Fist and melee damage." },
  { key: "defence", icon: "🛡️", name: "Defence", text: "Damage resistance, armour and shields." },
  { key: "agility", icon: "💨", name: "Agility", text: "Chance to dodge incoming attacks." },
  { key: "accuracy", icon: "🎯", name: "Accuracy", text: "Chance to hit, especially with arrows." }
];
function trainingMessage(text,type="info"){const el=document.getElementById("training-message");el.className=`training-message ${type}`;el.textContent=text;}
function number(value){return Number(value||0).toLocaleString("en-GB");}
async function loadTrainingGrounds(){try{const{data:{user}}=await supabaseClient.auth.getUser();if(!user){location.href="login.html";return;}const{data,error}=await supabaseClient.from("players").select("silver,strength,defence,agility,accuracy").eq("id",user.id).single();if(error)throw error;document.getElementById("training-silver").textContent=number(data.silver);const total=trainingStats.reduce((sum,stat)=>sum+Number(data[stat.key]||0),0);document.getElementById("total-warrior-stats").innerHTML=`<div class="battle-total-icon">⚔️</div><div><span>Total Warrior Stats</span><strong>${number(total)}</strong></div><p>Your combined Strength, Defence, Agility and Accuracy.</p>`;document.getElementById("battle-stat-grid").innerHTML=trainingStats.map(stat=>{const current=Number(data[stat.key]||0);const gain=Math.max(1,Math.floor(current*0.10));return `<article class="battle-stat-card"><div class="battle-stat-icon">${stat.icon}</div><h2>${stat.name}</h2><strong>${number(current)}</strong><p>${stat.text}</p><div class="battle-stat-gain">Next session: <strong>+${number(gain)}</strong> (10%)</div><button type="button" onclick="trainBattleStat('${stat.key}')" ${Number(data.silver)<250?"disabled":""}>Train for 250 Silver</button></article>`;}).join("");}catch(error){console.error(error);trainingMessage(`❌ ${error.message}`,"error");}}
async function trainBattleStat(stat){if(trainingBusy)return;trainingBusy=true;try{trainingMessage("Training in progress…");const{data,error}=await supabaseClient.rpc("train_battle_stat",{target_stat:stat});if(error)throw error;trainingMessage(`✅ ${data.stat_name[0].toUpperCase()+data.stat_name.slice(1)} increased by ${number(data.stat_gain)} to ${number(data.stat_after)}.`,"success");await loadTrainingGrounds();}catch(error){trainingMessage(`❌ ${error.message}`,"error");}finally{trainingBusy=false;}}
window.trainBattleStat=trainBattleStat;loadTrainingGrounds();
