-- Midgard Legacy: Friends and enemies
-- Run this file once in Supabase SQL Editor.

create table if not exists public.player_relations (
    id bigint generated by default as identity primary key,
    owner_id uuid not null,
    target_id uuid not null,
    relation_type text not null,
    created_at timestamptz not null default now(),

    constraint player_relations_owner_id_fkey
        foreign key (owner_id)
        references public.players(id)
        on delete cascade,

    constraint player_relations_target_id_fkey
        foreign key (target_id)
        references public.players(id)
        on delete cascade,

    constraint player_relations_type_check
        check (relation_type in ('friend', 'enemy')),

    constraint player_relations_not_self_check
        check (owner_id <> target_id),

    constraint player_relations_owner_target_key
        unique (owner_id, target_id)
);

create index if not exists player_relations_owner_type_idx
    on public.player_relations(owner_id, relation_type);

alter table public.player_relations enable row level security;

drop policy if exists "Players can view own relations"
    on public.player_relations;

create policy "Players can view own relations"
    on public.player_relations
    for select
    to authenticated
    using (auth.uid() = owner_id);

drop policy if exists "Players can add own relations"
    on public.player_relations;

create policy "Players can add own relations"
    on public.player_relations
    for insert
    to authenticated
    with check (
        auth.uid() = owner_id
        and owner_id <> target_id
        and relation_type in ('friend', 'enemy')
    );

drop policy if exists "Players can change own relations"
    on public.player_relations;

create policy "Players can change own relations"
    on public.player_relations
    for update
    to authenticated
    using (auth.uid() = owner_id)
    with check (
        auth.uid() = owner_id
        and owner_id <> target_id
        and relation_type in ('friend', 'enemy')
    );

drop policy if exists "Players can remove own relations"
    on public.player_relations;

create policy "Players can remove own relations"
    on public.player_relations
    for delete
    to authenticated
    using (auth.uid() = owner_id);
