-- Safe public player-number setup.

alter table public.players
add column if not exists player_number bigint
generated by default as identity;

create unique index if not exists
players_player_number_key
on public.players(player_number);

update public.players
set player_number = default
where player_number is null;

select setval(
    pg_get_serial_sequence(
        'public.players',
        'player_number'
    ),
    greatest(
        coalesce(
            (
                select max(player_number)
                from public.players
            ),
            1
        ),
        1
    )
);
