-- Midgard Legacy
-- Central activity logging and notification groundwork.
-- Run after migrations 004 and 005.

begin;

create table if not exists public.player_activity_log (
    id bigint generated by default as identity primary key,
    player_id uuid not null references public.players(id) on delete cascade,
    username text,
    activity_type text not null,
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists player_activity_log_player_created_idx
on public.player_activity_log(player_id, created_at desc);

alter table public.player_activity_log enable row level security;

drop policy if exists "Players read own activity"
on public.player_activity_log;

create policy "Players read own activity"
on public.player_activity_log
for select
to authenticated
using (auth.uid() = player_id);

create or replace function public.log_player_activity(
    p_player_id uuid,
    p_activity_type text,
    p_details jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_id bigint;
begin
    if auth.uid() is not null
       and auth.uid() <> p_player_id then
        raise exception 'Players may log only their own activity';
    end if;

    insert into public.player_activity_log (
        player_id,
        username,
        activity_type,
        details
    )
    select
        p.id,
        p.username,
        p_activity_type,
        coalesce(p_details, '{}'::jsonb)
    from public.players p
    where p.id = p_player_id
    returning id into v_id;

    return v_id;
end;
$$;

grant execute on function public.log_player_activity(uuid, text, jsonb)
to authenticated;

create table if not exists public.player_notifications (
    id bigint generated by default as identity primary key,
    player_id uuid not null references public.players(id) on delete cascade,
    notification_type text not null default 'system',
    title text not null,
    message text not null,
    icon text not null default '🔔',
    link text,
    unique_key text,
    is_read boolean not null default false,
    created_at timestamptz not null default now(),
    read_at timestamptz,
    unique (player_id, unique_key)
);

create index if not exists player_notifications_unread_idx
on public.player_notifications(player_id, is_read, created_at desc);

alter table public.player_notifications enable row level security;

drop policy if exists "Players read own notifications"
on public.player_notifications;

create policy "Players read own notifications"
on public.player_notifications
for select
to authenticated
using (auth.uid() = player_id);

drop policy if exists "Players update own notifications"
on public.player_notifications;

create policy "Players update own notifications"
on public.player_notifications
for update
to authenticated
using (auth.uid() = player_id)
with check (auth.uid() = player_id);

create or replace function public.create_player_notification(
    p_player_id uuid,
    p_type text,
    p_title text,
    p_message text,
    p_icon text default '🔔',
    p_link text default null,
    p_unique_key text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_id bigint;
begin
    if auth.uid() is not null
       and auth.uid() <> p_player_id then
        raise exception 'Players may create only their own notification';
    end if;

    insert into public.player_notifications (
        player_id,
        notification_type,
        title,
        message,
        icon,
        link,
        unique_key
    )
    values (
        p_player_id,
        coalesce(p_type, 'system'),
        p_title,
        p_message,
        coalesce(p_icon, '🔔'),
        p_link,
        p_unique_key
    )
    on conflict (player_id, unique_key)
    do nothing
    returning id into v_id;

    return v_id;
end;
$$;

grant execute on function public.create_player_notification(
    uuid, text, text, text, text, text, text
) to authenticated;

-- Achievement definitions make milestones data-driven.
create table if not exists public.achievement_definitions (
    achievement_key text primary key,
    statistic_column text,
    threshold bigint,
    title text not null,
    message text not null,
    icon text not null default '🏆',
    is_active boolean not null default true
);

create table if not exists public.player_achievements (
    id bigint generated by default as identity primary key,
    player_id uuid not null references public.players(id) on delete cascade,
    achievement_key text not null references public.achievement_definitions(achievement_key),
    unlocked_at timestamptz not null default now(),
    unique (player_id, achievement_key)
);

alter table public.player_achievements enable row level security;

drop policy if exists "Players read own achievements"
on public.player_achievements;

create policy "Players read own achievements"
on public.player_achievements
for select
to authenticated
using (auth.uid() = player_id);

insert into public.achievement_definitions (
    achievement_key,
    statistic_column,
    threshold,
    title,
    message,
    icon
)
values
    (
        'trees_chopped_100',
        'trees_chopped',
        100,
        'Woodland Worker',
        'You have chopped 100 trees. The village now knows you as a dependable woodsman.',
        '🌲'
    ),
    (
        'trees_chopped_1000',
        'trees_chopped',
        1000,
        'Legend of the Forest',
        'You have chopped 1,000 trees. Even the oldest woodsmen now know your name.',
        '🌲'
    ),
    (
        'ore_mined_1000',
        'ore_mined',
        1000,
        'Master of the Bog',
        'You have gathered 1,000 pieces of ore from the earth.',
        '⛏️'
    ),
    (
        'bars_forged_1000',
        'bars_forged',
        1000,
        'Forged in Fire',
        'You have forged 1,000 iron bars.',
        '🔥'
    )
on conflict (achievement_key)
do update set
    statistic_column = excluded.statistic_column,
    threshold = excluded.threshold,
    title = excluded.title,
    message = excluded.message,
    icon = excluded.icon;

commit;
