-- Hunting weapon unlocks and timed Village Forge orders.

alter table public.gathering_resource_nodes
    add column if not exists required_hunting_weapon text
    check (required_hunting_weapon is null or required_hunting_weapon in ('spear','bow'));

update public.gathering_resource_nodes
set required_hunting_weapon = case
    when node_key in ('hunt_rabbit','hunt_game_bird') then 'spear'
    when profession = 'hunting' then 'bow'
    else required_hunting_weapon
end
where profession = 'hunting';

create table if not exists public.village_forge_orders (
    id bigint generated by default as identity primary key,
    player_id uuid not null references public.players(id) on delete cascade,
    product_key text not null check (product_key in ('iron_arrowhead','spearhead')),
    batches_total integer not null check (batches_total > 0),
    batches_completed integer not null default 0 check (batches_completed >= 0),
    started_at timestamptz not null default now(),
    next_batch_at timestamptz not null default (now() + interval '20 seconds'),
    completed_at timestamptz,
    status text not null default 'working' check (status in ('working','completed'))
);

alter table public.village_forge_orders enable row level security;

drop policy if exists village_forge_orders_select_own on public.village_forge_orders;
create policy village_forge_orders_select_own
on public.village_forge_orders for select
to authenticated
using (player_id = auth.uid());

grant select on public.village_forge_orders to authenticated;

create or replace function public.process_village_forge_orders(p_player uuid default auth.uid())
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_order record;
    v_due integer;
    v_remaining integer;
    v_to_complete integer;
    v_item_id bigint;
    v_quantity bigint;
    v_total_added bigint := 0;
begin
    if p_player is null or p_player <> auth.uid() then
        raise exception 'Sign in required.';
    end if;

    for v_order in
        select *
        from public.village_forge_orders
        where player_id = p_player and status = 'working'
        for update
    loop
        if now() < v_order.next_batch_at then
            continue;
        end if;

        v_remaining := v_order.batches_total - v_order.batches_completed;
        v_due := 1 + floor(extract(epoch from (now() - v_order.next_batch_at)) / 20)::integer;
        v_to_complete := least(v_remaining, greatest(0, v_due));

        if v_to_complete <= 0 then
            continue;
        end if;

        select id into v_item_id
        from public.items
        where lower(name) = case v_order.product_key
            when 'iron_arrowhead' then 'iron arrowhead'
            else 'spearhead'
        end
        limit 1;

        v_quantity := v_to_complete * 25;
        perform public.grant_gathered_item(p_player, v_item_id, v_quantity);
        v_total_added := v_total_added + v_quantity;

        update public.village_forge_orders
        set batches_completed = batches_completed + v_to_complete,
            next_batch_at = next_batch_at + make_interval(secs => v_to_complete * 20),
            status = case when batches_completed + v_to_complete >= batches_total then 'completed' else 'working' end,
            completed_at = case when batches_completed + v_to_complete >= batches_total then now() else null end
        where id = v_order.id;
    end loop;

    return jsonb_build_object('items_added', v_total_added);
end;
$$;

create or replace function public.queue_village_forge_order(p_product_key text, p_batches integer)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_player uuid := auth.uid();
    v_bars_id bigint;
    v_required bigint;
    v_order_id bigint;
begin
    if v_player is null then raise exception 'Sign in required.'; end if;
    if p_product_key not in ('iron_arrowhead','spearhead') then raise exception 'Unknown Village Forge product.'; end if;
    if p_batches < 1 or p_batches > 1000 then raise exception 'Choose between 1 and 1,000 batches.'; end if;

    perform public.process_village_forge_orders(v_player);

    if exists (
        select 1 from public.village_forge_orders
        where player_id=v_player and status='working'
    ) then
        raise exception 'Bjørn is already working on an order for you.';
    end if;

    select id into v_bars_id from public.items where lower(name)='iron bar' limit 1;
    v_required := p_batches;

    if public.shared_item_quantity(v_player, v_bars_id) < v_required then
        raise exception 'You need % Iron Bars.', v_required;
    end if;

    perform public.consume_shared_item(v_player, v_bars_id, v_required);

    insert into public.village_forge_orders(player_id, product_key, batches_total)
    values(v_player, p_product_key, p_batches)
    returning id into v_order_id;

    return jsonb_build_object(
        'order_id', v_order_id,
        'product_key', p_product_key,
        'batches', p_batches,
        'bars_used', v_required,
        'items_per_batch', 25,
        'seconds_per_batch', 20
    );
end;
$$;

create or replace function public.get_village_forge_status()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_player uuid := auth.uid();
    v_order record;
begin
    if v_player is null then raise exception 'Sign in required.'; end if;
    perform public.process_village_forge_orders(v_player);

    select * into v_order
    from public.village_forge_orders
    where player_id=v_player
    order by id desc
    limit 1;

    if not found then return jsonb_build_object('order', null); end if;

    return jsonb_build_object('order', jsonb_build_object(
        'id', v_order.id,
        'product_key', v_order.product_key,
        'batches_total', v_order.batches_total,
        'batches_completed', v_order.batches_completed,
        'items_completed', v_order.batches_completed * 25,
        'items_total', v_order.batches_total * 25,
        'next_batch_at', v_order.next_batch_at,
        'status', v_order.status
    ));
end;
$$;

grant execute on function public.process_village_forge_orders(uuid) to authenticated;
grant execute on function public.queue_village_forge_order(text, integer) to authenticated;
grant execute on function public.get_village_forge_status() to authenticated;

-- Show hunting weapon requirements and ownership on the gathering screen.
create or replace function public.get_my_gathering_screen()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_player uuid := auth.uid();
    v_skills public.skills%rowtype;
    v_nodes jsonb;
    v_has_spear boolean;
    v_has_bow boolean;
begin
    if v_player is null then raise exception 'Sign in required.'; end if;
    insert into public.skills(player_id) values(v_player) on conflict(player_id) do nothing;
    select * into v_skills from public.skills where player_id=v_player;

    select exists(
        select 1 from public.inventory inv join public.items i on i.id=inv.item_id
        where inv.player_id=v_player and inv.quantity>0 and lower(i.name) like '%spear%'
    ) into v_has_spear;

    select exists(
        select 1 from public.inventory inv join public.bow_definitions b on b.item_id=inv.item_id
        where inv.player_id=v_player and inv.quantity>0
    ) into v_has_bow;

    select coalesce(jsonb_agg(node_row order by node_row->>'profession',(node_row->>'required_skill_level')::integer,(node_row->>'sort_order')::integer),'[]'::jsonb)
    into v_nodes
    from (
        select jsonb_build_object(
            'node_key',n.node_key,'profession',n.profession,'display_name',n.display_name,
            'description',n.description,'icon',n.icon,'minimum_reward',n.minimum_reward,
            'maximum_reward',n.maximum_reward,'energy_cost',n.energy_cost,
            'required_skill_level',n.required_skill_level,'sort_order',n.sort_order,
            'primary_item_name',primary_item.name,'bonus_item_name',bonus_item.name,
            'required_item_name',required_item.name,
            'required_hunting_weapon',n.required_hunting_weapon,
            'has_required_hunting_weapon',case n.required_hunting_weapon when 'spear' then v_has_spear when 'bow' then v_has_bow else true end,
            'has_required_item',case when n.required_item_id is null then true else public.shared_item_quantity(v_player,n.required_item_id)>=1 end,
            'current_skill_level',case n.profession
                when 'woodcutting' then coalesce(v_skills.woodcutting_level,public.midgard_skill_level(v_skills.woodcutting_xp))
                when 'mining' then coalesce(v_skills.mining_level,public.midgard_skill_level(v_skills.mining_xp))
                when 'foraging' then coalesce(v_skills.foraging_level,public.midgard_skill_level(v_skills.foraging_xp))
                when 'fishing' then coalesce(v_skills.fishing_level,public.midgard_skill_level(v_skills.fishing_xp))
                when 'hunting' then coalesce(v_skills.hunting_level,public.midgard_skill_level(v_skills.hunting_xp)) else 1 end
        ) node_row
        from public.gathering_resource_nodes n
        join public.items primary_item on primary_item.id=n.primary_item_id
        left join public.items bonus_item on bonus_item.id=n.bonus_item_id
        left join public.items required_item on required_item.id=n.required_item_id
        where n.is_active=true
    ) rows_for_json;

    return jsonb_build_object(
        'skill_levels',jsonb_build_object('woodcutting',coalesce(v_skills.woodcutting_level,1),'mining',coalesce(v_skills.mining_level,1),'foraging',coalesce(v_skills.foraging_level,1),'fishing',coalesce(v_skills.fishing_level,1),'hunting',coalesce(v_skills.hunting_level,1)),
        'skill_xp',jsonb_build_object('woodcutting',coalesce(v_skills.woodcutting_xp,0),'mining',coalesce(v_skills.mining_xp,0),'foraging',coalesce(v_skills.foraging_xp,0),'fishing',coalesce(v_skills.fishing_xp,0),'hunting',coalesce(v_skills.hunting_xp,0)),
        'nodes',v_nodes
    );
end;
$$;

-- Hunting uses the weapon assigned to each animal. Knife only preserves hides/pelts.
create or replace function public.gather_resource_025_core(p_node_key text, p_actions integer default 1)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_player uuid := auth.uid();
    v_profession text;
    v_required_weapon text;
    v_result jsonb;
    v_finds jsonb := '{}'::jsonb;
    v_arrow_id bigint;
    v_bow record;
    v_has_spear boolean := false;
    v_knife_owned boolean := false;
    v_bonus_item text;
    v_bonus_qty integer;
    v_recovered integer := 0;
    v_roll integer;
begin
    if v_player is null then raise exception 'Sign in required.'; end if;
    select profession,required_hunting_weapon into v_profession,v_required_weapon
    from public.gathering_resource_nodes where node_key=p_node_key and is_active;

    if v_profession='hunting' then
        if v_required_weapon='spear' then
            select exists(
                select 1 from public.inventory inv join public.items i on i.id=inv.item_id
                where inv.player_id=v_player and inv.quantity>0 and lower(i.name) like '%spear%'
            ) into v_has_spear;
            if not v_has_spear then raise exception 'This animal requires a crafted Spear.'; end if;
        else
            select i.id,i.name,b.damage,b.maximum_durability into v_bow
            from public.inventory inv join public.items i on i.id=inv.item_id join public.bow_definitions b on b.item_id=i.id
            where inv.player_id=v_player and inv.quantity>0 order by b.damage desc limit 1;
            if not found then raise exception 'This animal requires a crafted Bow.'; end if;
            select id into v_arrow_id from public.items where lower(name)='arrow' limit 1;
            if public.shared_item_quantity(v_player,v_arrow_id)<greatest(1,p_actions) then raise exception 'You need one Arrow for every hunting action.'; end if;
            perform public.consume_shared_item(v_player,v_arrow_id,greatest(1,p_actions));
        end if;

        select exists(select 1 from public.player_profession_equipment where player_id=v_player and equipment_key='hunting_knife' and current_durability>0) into v_knife_owned;
    end if;

    v_result:=public.gather_resource_024_core(p_node_key,p_actions);

    if v_profession='woodcutting' then
        v_finds:=public.grant_woodcutting_finds(v_player,p_node_key,p_actions);
        v_result:=v_result||jsonb_build_object('woodcutting_finds',v_finds);
    elsif v_profession='hunting' then
        if v_required_weapon='bow' then
            for v_roll in 1..greatest(1,p_actions) loop if random()<0.60 then v_recovered:=v_recovered+1; end if; end loop;
            if v_recovered>0 then perform public.grant_gathered_item(v_player,v_arrow_id,v_recovered); end if;
        end if;

        v_bonus_item:=v_result->>'bonus_item';
        v_bonus_qty:=coalesce((v_result->>'bonus_quantity')::integer,0);
        if not v_knife_owned and v_bonus_qty>0 and v_bonus_item is not null and (lower(v_bonus_item) like '%hide%' or lower(v_bonus_item) like '%pelt%') then
            perform public.consume_shared_item(v_player,(select id from public.items where lower(name)=lower(v_bonus_item) limit 1),v_bonus_qty);
            v_result:=jsonb_set(v_result,'{bonus_quantity}','0'::jsonb,true)||jsonb_build_object('knife_required_for_bonus',true,'discarded_bonus',v_bonus_item);
        end if;

        v_result:=v_result||jsonb_build_object(
            'hunting_weapon',v_required_weapon,
            'weapon_name',case when v_required_weapon='spear' then 'Spear' else v_bow.name end,
            'arrows_used',case when v_required_weapon='bow' then greatest(1,p_actions) else 0 end,
            'arrows_recovered',v_recovered,
            'hunting_knife_owned',v_knife_owned
        );
    end if;
    return v_result;
end;
$$;

-- Remove the old wrapper rules that forced both a knife and an equipped bow.
create or replace function public.gather_resource(p_node_key text, p_actions integer default 1)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_player uuid:=auth.uid(); v_profession text; v_tool text; v_owned record; v_result jsonb; v_quantity bigint; v_item_name text;
begin
    if v_player is null then raise exception 'Sign in required.'; end if;
    select profession into v_profession from public.gathering_resource_nodes where node_key=p_node_key and is_active=true;
    if v_profession='woodcutting' then v_tool:='iron_axe'; end if;
    if v_profession='mining' then v_tool:='iron_pickaxe'; end if;
    if v_tool is not null then
        select * into v_owned from public.player_profession_equipment where player_id=v_player and equipment_key=v_tool for update;
        if not found then raise exception 'You need an % in your tool belt.',case when v_tool='iron_axe' then 'Iron Axe' else 'Iron Pickaxe' end; end if;
        if v_owned.current_durability<p_actions then raise exception 'Your tool is too damaged. Repair it before doing % actions.',p_actions; end if;
    end if;
    v_result:=public.gather_resource_025_core(p_node_key,p_actions);
    if v_tool is not null then
        update public.player_profession_equipment set current_durability=greatest(0,current_durability-p_actions),updated_at=now() where player_id=v_player and equipment_key=v_tool;
        v_result:=v_result||jsonb_build_object('tool_durability_remaining',(select current_durability from public.player_profession_equipment where player_id=v_player and equipment_key=v_tool));
    end if;
    v_quantity:=coalesce((v_result->>'primary_quantity')::bigint,0); v_item_name:=lower(coalesce(v_result->>'primary_item',''));
    perform public.record_task_event(v_player,'gather_actions',greatest(1,p_actions)); perform public.record_task_event(v_player,'gather_any',v_quantity);
    if v_item_name like '%log%' then perform public.record_task_event(v_player,'gather_logs',v_quantity); end if;
    if v_item_name like '%stick%' then perform public.record_task_event(v_player,'gather_sticks',v_quantity); end if;
    if v_profession='woodcutting' then perform public.record_task_event(v_player,'gather_woodcutting',v_quantity); end if;
    if v_profession='mining' then perform public.record_task_event(v_player,'gather_mining',v_quantity); end if;
    if v_profession='foraging' then perform public.record_task_event(v_player,'gather_foraging',v_quantity); end if;
    return v_result;
end;
$$;
